{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "API - HORUS",
    "description": "Documentação da API HORUS"
  },
  "host": "localhost:3000",
  "basePath": "",
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/cadastrar-produto/": {
      "post": {
        "tags": [
          "Produto"
        ],
        "summary": "Cadastro de Produto",
        "description": "Teste de descricao",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/get-produto/": {
      "get": {
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/update-produto/": {
      "patch": {
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/delete-produto/{id}": {
      "delete": {
        "tags": [
          "Produto"
        ],
        "summary": "Delete Produto",
        "description": "Teste de descricao",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {}
      }
    },
    "/cadastrar-cliente/": {
      "post": {
        "description": "",
        "parameters": [],
        "responses": {}
      }
    },
    "/get-cliente/": {
      "get": {
        "description": "",
        "parameters": [],
        "responses": {}
      }
    },
    "/update-cliente/": {
      "patch": {
        "description": "",
        "parameters": [],
        "responses": {}
      }
    },
    "/delete-cliente/{id}": {
      "delete": {
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {}
      }
    }
  }
}